### ISSUE TITLE
plyer.uniqueid.id causes crash on Android with sdl2

### ISSUE THREAD

**Issue by WillDHB** [kivy/plyer#245]
I've found that attempting to access plyer.uniqueid.id causes the app to crash immediately (without any normal exception propagation) on Android.  This only happened after switching the backend to sdl2, however; prior to that, everything seemed to work fine (I have been unable to revert back to the old backend to verify this).  I have tested this out on two different Android devices with the same result.

**Comment by trivedigaurav** [comment]
Could you include the error log please?

**Comment by WillDHB** [comment]
Probably.

[deviceid_log.txt](https://github.com/kivy/plyer/files/629316/deviceid_log.txt)

**Comment by WillDHB** [comment]
After messing with this some more, it looks like just about anything from plyer causes the issue.  After messing around with it, it looks like the problem happens in android/__init__.py, on the line:
    activity = PythonActivity.mActivity

**Comment by WillDHB** [comment]
It looks like the problem is that org.renpy.android.PythonActivity only works with the old toolchain; org.kivy.android.PythonActivity should be used with the new toolchain.

**Comment by KeyWeeUsr** [comment]
> It looks like the problem is that org.renpy.android.PythonActivity only works with the old toolchain; org.kivy.android.PythonActivity should be used with the new toolchain.

Not necessarily. The problem will happen if you don't include `android` in your `requirements` since that actually resolves what `JAVA_NAMESPACE` is used or better said, that thing chooses between `renpy` or `kivy`, otherwise it just fallbacks to the old namespace [`org.renpy.android`](https://github.com/kivy/plyer/blob/1a9352f85f49177a1a88c2a3326e4d2b6544a14a/plyer/platforms/android/__init__.py#L10).
