### ISSUE TITLE
plyer examples app always crashes in android phones, It says "Unfortunately "Name of app" has stopped working."

### ISSUE THREAD

**Issue by Akash3194** [kivy/plyer#349]
Somebody please help me, i am having really very hard time using plyer, whenever i make apk files of any example given in plyer folders and run them on android. It always says "Unfortunately app has stopped working".

**Comment by malverick** [comment]
Hi @Akash3194 , please make sure you have enabled `USB debugging` in your android phone. If the problem still persists, then I would recommend you to share the android logs here so that we can see where's the problem.
For logs, while running any plyer app, connect your mobile with your laptop and then run this command on terminal,
`adb logcat python:V *:S`

**Comment by Akash3194** [comment]
Hello @malverick thanx a lot, that you replied for this issue but i think this issue reached a lil bit late to you, i had solved this problem, i replaced kivy to git+https://github.com/kivy/plyer.git in requirements and added android and hostpython2, that solved my problem and now apk works fine. Can i just ask how to reduce the apk size of apps because a simple apps takes 40-50mb and after running it, it increases to 110-140 mb. Thankyou again

**Comment by malverick** [comment]
When you try to build apk using new p4a toolchain, all the recipes are build irrespective of whether you need them in your app or not. I think this causes the app to consume so much space. Maybe you can try to build only those recipes which you need in your app and ignore others while building the apk.

**Comment by Akash3194** [comment]
Thanks a lot.
