### ISSUE TITLE
Plyer Email

### ISSUE THREAD

**Issue by Archaeus6** [kivy/plyer#420]
I just learned about this great library and have been experimenting creating simple apps that use its features. I managed to make a really cool wikipedia api app that has a section to email a current label. On Pydroid3 Android app it runs great, and when I run it in linux it also works great. Once I build with Buildozer the plyer email function fails. Logcat is nothing distinct that I can read, just window death. 

I built with python 2
- requirements: kivy, requests, openssl, plyer,
- fullscreen: 0
-permissions: INTERNET

why will it not allow access to the media chooser section of the OS and launch native email like it does on all other platforms? Is there another permission I need to add? Thanks for any help.

**Comment by KeyWeeUsr** [comment]
Without the log we can't really help you. Also, I've tested email example from the latest plyer version and it works just fine. These are the [permissions](https://github.com/kivy/python-for-android/blob/33a058db29a4a1a0b4e3396140a674ea485789e2/testapps/testlauncherreboot_setup/sdl2.py#L65), however it should work without any permission because it's just an `Intent`. Check your app code and requirements.
