### ISSUE TITLE
app crashes right after plyer.wifi.start_scanning()

### ISSUE THREAD

**Issue by mahomahomaho** [kivy/plyer#421]
Hi, 

I have noticed that plyer.wifi.start_scanning() crashes android app. I tried to build plyer's wifi example, with attached buildozer.spec and it crashes as in logs:https://gist.github.com/mahomahomaho/91072fc5631b1d3cd6690f68caf32a11

buildozer: 

https://gist.github.com/mahomahomaho/4979e24cf90642f88ccdc92baa2b0506

**Comment by KeyWeeUsr** [comment]
I believe this is due to this line:

    JNI DETECTED ERROR IN APPLICATION: static jfieldID 0xe85cc014 not valid for class java.lang.Class<org.renpy.android.PythonActivity>

i.e. `autoclass('org.renpy.android.PythonActivity')` call. Anyway, even if you used `org.kivy.android.PythonActivity`, the Wifi isn't implemented for android right now, therefore you'd most likely got only the facade object and for the `start_scanning()` call [`NotImplementedError`](https://github.com/kivy/plyer/blob/ee44e6e786f99ba5d620fb66ce558c1bc50ffc54/plyer/facades/wifi.py#L115).

To check whether there is an implementation either check `README.md` or [`platforms`](https://github.com/kivy/plyer/tree/master/plyer/platforms) folder.
