### ISSUE TITLE
camera cant save picture on ios

### ISSUE THREAD

**Issue by d0kyuan** [kivy/plyer#456]
camera cant save picture on ios

**Comment by KeyWeeUsr** [comment]
Please provide basic config (python version, plyer version, ios, version) + logs and a minimal working example (try to run with the example on your device first). Perhaps you are missing a permission or the folder is incorrect. Try to adjust the final destination manually and provide more info.

**Comment by d0kyuan** [comment]
i use camera example for kivy-ios , but when i take a picture and click use photo commad line will show  ```
2018-10-19 09:27:11.927949+0800 pathtest[1848:706005] IIOImageWriteSession:115: cannot create: '/private/var/containers/Bundle/Application/7D8D91B1-269C-4EC3-91A5-B2CE9E9A8655/pathtest.app/YourApp/enter_file_name_here.jpg.sb-2639e15e-RZCqwQ'
         error = 1 (Operation not permitted)
```
photo not save !

**Comment by KeyWeeUsr** [comment]
@d0kyuan I believe this is a permission issue due to incorrect path regarding iOS policy of where you actually can write to a file. See [this answer](https://stackoverflow.com/a/11078682/5994041) or use a path similar to these:

    /private/var/mobile/Containers/Data/Application/<app id>/Documents/photo.jpg
    /private/var/containers/Bundle/Application/<app id>/Documents/photo.jpg

I don't have an access to any iOS device, so I can't help more with that. Please come visit https://chat.kivy.org.
