### ISSUE TITLE
Editing the buildozer.spec pyjnius files

### ISSUE THREAD

**Issue by jjccvt** [kivy/plyer#508]
I have looked at the issue as below, but i dont know where to edit the pyjnius file to replace all the 
"org/renpy/android/PythonActivity" to "activity = autoclass('org.kivy.android.PythonActivity')"

jnius.JavaException: Class not found 'org/renpy/android/PythonActivity' #330

**Comment by Python3-8** [comment]
Maybe you could find where the `pyjnius` module is installed, make a modified copy of it, and paste it in your app directory. This way you don't have to specify the `pyjnius` requirement in your `buildozer.spec` file and you still have access to the `pyjnius` module.

**Comment by Julian-O** [comment]
👋 Sorry to hear you are having difficulties; Kivy unites a number of different technologies, so building apps can be temperamental.

We try to use GitHub issues only to track work for developers to do to fix bugs and add new features to Buildozer. This issue should be closed, because it doesn't describe a bug in Buildozer.

There is a mailing list and a Discord channel to support Kivy users debugging their own systems, which should be able to help. They are linked in the [ReadMe](https://github.com/kivy/buildozer#support).

Of course, if it turns out you have stumbled over a bug in Buildozer, we do want to hear about it here. The support channels should be able to help you craft an appropriate bug report.
