### ISSUE TITLE
No notification icons on Linux (Gnome)

### ISSUE THREAD

**Issue by AlexP11223** [kivy/plyer#514]
Looks like the notification icon is not shown in Gnome (tested on Ubuntu 18.04, PopOS 19.04).

I am pretty sure that Gnome supports icons in the notifications, for example it works for Firefox extensions, and other apps.

![](https://i.imgur.com/5gc12Yh.png)

On Windows the same code works fine, but in Gnome it shows only text. https://github.com/AlexP11223/gdrive_link_transformer/blob/d3e3fdd2ffd6f778f510d7ac75eddfaaf8cd23f3/gdrive_link_transformer/gdrive_direct_link.py#L59

```
notification.notify(
    title='...',
    app_icon=os.path.join(resource_dir(), 'icon') + '.ico' if platform == "win" else '.png',
    message='...')
```

![](https://i.imgur.com/xoyTndy.png)

**Comment by Franccisco** [comment]
I was checking your code and the problem is not related to plyer. Look at that line:

https://github.com/AlexP11223/gdrive_link_transformer/blob/d3e3fdd2ffd6f778f510d7ac75eddfaaf8cd23f3/gdrive_link_transformer/gdrive_direct_link.py#L61

If you do
```python3
print(os.path.join(resource_dir(), "icon") + ".ico" if platform == "win" else ".png")
```

you'll only get the extension as result. That's why you weren't seeing any icon. To solve this, try adding a parenthesis, like this:

```python3
os.path.join(resource_dir(), "icon") + (".ico" if platform == "win" else ".png")
```

As this has nothing to do with plyer, you should close this.

**Comment by AlexP11223** [comment]
Yeah, thanks.
