### ISSUE TITLE
FileChooser on Android: "on selection" fires multiple times.

### ISSUE THREAD

**Issue by Zen-CODE** [kivy/plyer#530]
When using a minimal example (as attached), the "on_selection" callback is called 2x for the second selection, 3x for the third selection, 4x for the fourth etc.

Tested using:
    plyer==1.4.2
    kivy==1.11.1
    Android 9

This example demonstrates the bug: https://gist.github.com/Zen-CODE/c00344a0fee5224afe31166bcaa7cb17

**Comment by Franccisco** [comment]
The problem is here:
https://github.com/kivy/plyer/blob/46216b2c496c7304c8b82cff41f1c7f8a79006bd/plyer/platforms/android/filechooser.py#L120

Whenever ```_open_file``` is executed, there's a new bind to ```on_activity_result```. That's why you're watching an increasing calls to ```on_selection```. It can be fixed adding an ```unbind``` before that line. I'll make a commit to my fork fixing this. Please, try it and tell me if it works for you.

**Comment by Zen-CODE** [comment]
@Franccisco Please could you create a Pull Request and reference this ticket. That makes it way easier to test and merge. Thanks :-)
