### ISSUE TITLE
Does plyer allow you to open another app?

### ISSUE THREAD

**Issue by quadrismegistus** [kivy/plyer#577]
I am making an app which relies on another app being open in the background. (I need Tor Browser running so I can use its socks proxy to tor in my Kivy app.) Is there a way to open another app from within Kivy, maybe using Plyer? Thanks and sorry if this is not the right venue for the question.

**Comment by Python3-8** [comment]
You could use `pyjnius` which is used for accessing Java classes with Python. Plyer uses `pyjnius` on Android. I don't know how to use `pyjnius`, because I don't know Java. But with Java, you can do anything on Android. So Kivy might be able to add this feature to Plyer. This is actually a feature that even I wanted to use in my Kivy app. I don't know what 'Tor Browser' means, but if you want to open a web browser from your Kivy app, then you can use the `webbrowser` module that comes with Python.

**Comment by quadrismegistus** [comment]
Thanks so much! This is very helpful. I'm not at the stage of my app production where I'm customizing things by platform (Android, etc). But I'll rest assured that once I get there, there's a solution to be found. Thanks again

**Comment by Python3-8** [comment]
You're welcome.

**Comment by tshirtman** [comment]
(closing as it's not an issue, but more of a question)
