### ISSUE TITLE
Feature Request: Add Intent to Android Gallery(for Pictures)

### ISSUE THREAD

**Issue by kengoon** [kivy/plyer#588]
adding the ability to open android gallery will be super cool. It will save a lot of developers time on manually coding thumbnails for images or videos in file manager

**Comment by tshirtman** [comment]
Plyer tries to provide features that are common to multiple platforms, so it would be good to have a good idea of what would be the behavior on at least ios, and possibly windows/osx/linux as well, what common behavior would be made accessible through the facade.

**Comment by kengoon** [comment]
i dont actually use ios and osx so I don't know how that will function but On windows OS file manager can be used In place of that or a kivy gallery that only locates images on the platform could be created(once tried that but having a lot of issues). Also I think that IOS has Photo Library, check this[http://omz-software.com/pythonista/docs/ios/photos.html](url). I have not used that though because i don't have access to IOS devices. I do believe that IOS has the API that supports that.

On Liniux and Windows file manager could be used or the kivy gallery

**Comment by tshirtman** [comment]
Yes, i don't use ios either, but i assume it has something similar, and i though about using file manager on desktop, but that's why i was concerned about a common api between the platform, as i'm not sure exactly what this facade would bring that the filechooser doesn't.

As i briefly looked at android api, there doesn't seem to be a common "photo gallery" intent to use directly, and "Gallery" rathers refer to a deprecated layout that was convenient to implement such views.

If you have more details about what you expect to see/which api that would wrap, to flush out a proposition, that would be helpful.

**Comment by kengoon** [comment]
i will dig more and get back to you, also I will be sending a link to a gist that shows how the kivy gallery works(that will be when I'm done with it). that's all I can do for now
