### ISSUE TITLE
Android camera app crash 

### ISSUE THREAD

**Issue by purushottam858** [kivy/plyer#605]
https://github.com/rainmaker29/Android-Camera/issues/2

please check  above app  , I tried to  clone this but failed to do with this error .

 Thanks in advance

**Comment by Julian-O** [comment]
👋 Sorry to hear you are having difficulties; Kivy unites a number of different technologies, so building apps can be temperamental.

We try to use GitHub issues only to track work for developers to do to fix bugs and add new features to Buildozer. This issue should be closed, because it doesn't describe a bug in Buildozer.

There is a mailing list and a Discord channel to support Kivy users debugging their own systems, which should be able to help. They are linked in the [ReadMe](https://github.com/kivy/buildozer#support).

Of course, if it turns out you have stumbled over a bug in Buildozer, we do want to hear about it here. The support channels should be able to help you craft an appropriate bug report.
