### ISSUE TITLE
Is there a way to get the values of spatialorientation without noise ?

### ISSUE THREAD

**Issue by MasterHansCoding** [kivy/plyer#660]
plyer/facades/spatialorientation.py

Do you have a filter to remove the noise or should we need to implement our own? Because I don't succeed.

BR,

kokottc

**Comment by Julian-O** [comment]
We try to use GitHub issues only to track work for developers to do to fix bugs and add new features to Buildozer. This issue should be closed, because it doesn't describe a bug in Buildozer.

There is a mailing list and a Discord channel to support Kivy users debugging their own systems, which should be able to help. They are linked in the [ReadMe](https://github.com/kivy/buildozer#support).
