### ISSUE TITLE
STT: Speech to Text not working for Android Device API 30 or more

### ISSUE THREAD

**Issue by znerl** [kivy/plyer#705]
https://github.com/kivy/plyer/issues/693

Similar problem as found at this link, however I am unable to get plyer.stt to work. 

Maybe there is someone out there who can help and would like to post a workaround

**Comment by ignamendi21** [comment]
did you find the solution?

**Comment by znerl** [comment]
Nope, stopped with that.--- Ursprüngliche Nachricht ---Von: ignamendi21 ***@***.***>Datum: 11.12.2022 22:34:51An: kivy/plyer ***@***.***>Betreff: Re: [kivy/plyer] STT: Speech to Text not working for Android Device  API 30 or more (Issue #705)
did you find the solution?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @github.com>

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/kivy/plyer/issues/705#issuecomment-1345662315",
"url": "https://github.com/kivy/plyer/issues/705#issuecomment-1345662315",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]


Versendet mit Emailn.de - Freemail

* Unbegrenzt Speicherplatz
* Eigenes Online-Büro
* 24h besten Mailempfang
* Spamschutz, Adressbuch

**Comment by ignamendi21** [comment]
: (

**Comment by Julian-O** [comment]
👋 Sorry to hear you are having difficulties; Kivy unites a number of different technologies, so developing apps can be temperamental.

We try to use GitHub issues only to track work for developers to do to fix bugs and add new features to this project. This issue is being closed, because it doesn't describe a bug in this project.

There is a mailing list and a Discord channel to support Kivy users debugging their own systems, which should be able to help. They are linked in the [ReadMe](https://github.com/kivy/buildozer#support).

Of course, if it turns out you have stumbled over a bug in this project, we do want to hear about it here. The support channels should be able to help you craft an appropriate bug report.
