### ISSUE TITLE
check and change screen rotation 

### ISSUE THREAD

**Issue by rain874** [kivy/plyer#714]
I would like to make a query to query the screen rotation and then, if for example Portrait is selected, rotate the screen to Landscape. 

In KivyMD, a certain screen should only be output in landscape and the whole thing should be ensured accordingly with Plyer. 

Currently I have each screen in a kv file and call a method in the main class. 

For a short example I would be grateful.

**Comment by RobertFlatt** [comment]
Not really a Plyer related question.

To act on screen orientation : https://github.com/Android-for-Python/c4k_photo_example/blob/main/applayout/photoscreen1.py#L59-L60

The layout for a given orientation is up to you. In the example this is just size_hint but could be more general.

For Android the above assumes `orientation = all` in buildozer.spec

**Comment by Julian-O** [comment]
👋 Sorry to hear you are having difficulties; Kivy unites a number of different technologies, so developing apps can be temperamental.

We try to use GitHub issues only to track work for developers to do to fix bugs and add new features to this project. This issue is being closed, because it doesn't describe a bug in this project.

There is a mailing list and a Discord channel to support Kivy users debugging their own systems, which should be able to help. They are linked in the [ReadMe](https://github.com/kivy/buildozer#support).

Of course, if it turns out you have stumbled over a bug in this project, we do want to hear about it here. The support channels should be able to help you craft an appropriate bug report.
