### ISSUE TITLE
speech to text 

### ISSUE THREAD

**Issue by purushottam858** [kivy/plyer#715]
i tried https://github.com/Abhishek-op/SR 

 and  https://github.com/kivy/plyer/blob/master/examples/speech2text/main.py .

in both cases  i am getting below error . please help me out .

and 

any other way to speech to text  ...??? 

10-14 15:01:15.124 22378 22378 I python  :  Traceback (most recent call last):
10-14 15:01:15.125 22378 22378 I python  :    File "jnius/jnius_proxy.pxi", line 156, in jnius.jnius.invoke0
10-14 15:01:15.126 22378 22378 I python  :    File "jnius/jnius_proxy.pxi", line 124, in jnius.jnius.py_invoke0
10-14 15:01:15.127 22378 22378 I python  :  AttributeError: 'list' object has no attribute 'invoke'
10-14 15:01:15.131 22378 22378 I python  :  Traceback (most recent call last):
10-14 15:01:15.132 22378 22378 I python  :    File "jnius/jnius_proxy.pxi", line 156, in jnius.jnius.invoke0
10-14 15:01:15.133 22378 22378 I python  :    File "jnius/jnius_proxy.pxi", line 124, in jnius.jnius.py_invoke0

**Comment by kuzeyron** [comment]
> i tried https://github.com/Abhishek-op/SR
> 
> and https://github.com/kivy/plyer/blob/master/examples/speech2text/main.py .
> 
> in both cases i am getting below error . please help me out .
> 
> and
> 
> any other way to speech to text ...???
> 
> 10-14 15:01:15.124 22378 22378 I python : Traceback (most recent call last): 10-14 15:01:15.125 22378 22378 I python : File "jnius/jnius_proxy.pxi", line 156, in jnius.jnius.invoke0 10-14 15:01:15.126 22378 22378 I python : File "jnius/jnius_proxy.pxi", line 124, in jnius.jnius.py_invoke0 10-14 15:01:15.127 22378 22378 I python : AttributeError: 'list' object has no attribute 'invoke' 10-14 15:01:15.131 22378 22378 I python : Traceback (most recent call last): 10-14 15:01:15.132 22378 22378 I python : File "jnius/jnius_proxy.pxi", line 156, in jnius.jnius.invoke0 10-14 15:01:15.133 22378 22378 I python : File "jnius/jnius_proxy.pxi", line 124, in jnius.jnius.py_invoke0

And you have set `android.permissions = INTERNET,RECORD_AUDIO` in the `buildozer.spec` file?
These days it might be needed to have runtime permissions. At least for recording I believe it's needed:
https://python-for-android.readthedocs.io/en/latest/apis/#runtime-permissions

**Comment by Julian-O** [comment]
👋 Sorry to hear you are having difficulties; Kivy unites a number of different technologies, so developing apps can be temperamental.

We try to use GitHub issues only to track work for developers to do to fix bugs and add new features to this project. This issue is being closed, because it doesn't describe a bug in this project.

There is a mailing list and a Discord channel to support Kivy users debugging their own systems, which should be able to help. They are linked in the [ReadMe](https://github.com/kivy/buildozer#support).

Of course, if it turns out you have stumbled over a bug in this project, we do want to hear about it here. The support channels should be able to help you craft an appropriate bug report.
