### ISSUE TITLE
Not work  filechooser.save_file(on_selection=f.read())

### ISSUE THREAD

**Issue by POMXARK** [kivy/plyer#757]
I'm trying to get this to work in win 11, is this functionality not finalized yet?
What do I need to open the save file dialog, and save the transferred content under any name

http://timgolden.me.uk/pywin32-docs/win32gui__GetSaveFileNameW_meth.html

```
    def save_file(self):
        # save_path = win32gui.GetSaveFileNameW(File='file_name')[0]
        save_path = filechooser.save_file()[0]
        with open(save_path, 'w') as file:
            file.write(str(self.cv2_params))
 ```
 
 as an option, read about the possibilities of api.

**Comment by Julian-O** [comment]
👋 Sorry to hear you are having difficulties; Kivy unites a number of different technologies, so developing apps can be temperamental.

We try to use GitHub issues only to track work for developers to do to fix bugs and add new features to this project. This issue is being closed, because it doesn't describe a bug in this project.

There is a mailing list and a Discord channel to support Kivy users debugging their own systems, which should be able to help. They are linked in the [ReadMe](https://github.com/kivy/buildozer#support).

Of course, if it turns out you have stumbled over a bug in this project, we do want to hear about it here. The support channels should be able to help you craft an appropriate bug report.
