### ISSUE TITLE
Gyroscope Not working 

### ISSUE THREAD

**Issue by Shuvadip-Ghosh** [kivy/plyer#758]
### I was writing a python app to get the gyroscope data and display it
```python
import kivy
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
import random
from plyer import gyroscope
gyroscope.enable()

kivy.require('1.9.0')

class Gyro(BoxLayout):
    def __init__(self):
        super(Gyro,self).__init__()

    def generate_num(self):
        while True:
            self.ids.no_labl.text = str(gyroscope.rotation)
        #self.ids.no_labl.text = str(random.randint(0,1000))

class controller(App):
    def build(self):
        return Gyro()

cont = controller()
cont.run()
```
### I also tried this
```python
import kivy
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
import random
from plyer import gyroscope

kivy.require('1.9.0')

class Gyro(BoxLayout):
    def __init__(self):
        super(Gyro,self).__init__()

    def generate_num(self):
        while True:
            self.ids.no_labl.text = str(gyroscope.rotation)
        #self.ids.no_labl.text = str(random.randint(0,1000))

class controller(App):
    def on_start(self):
        gyroscope.enable()
    def build(self):
        return Gyro()

Randno = controller()
Randno.run()
```
## My Kivy code
```
<Gyro>
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "Gyro data"
            font_size:64
            color:0.92,0.45,0
        Label:
            id: no_labl
            text:"-"
            font_size:64
        Button:
            text:"Generate"
            font_size: 32
            size: 50,100
            on_press: root.generate_num()
```

Is there any problem with my code.
When compiled with buildozer it is compiled perfectly but the button gets disabled when the apk file is runned in the phone.
Any fixes??

**Comment by Julian-O** [comment]
👋 Sorry to hear you are having difficulties; Kivy unites a number of different technologies, so developing apps can be temperamental.

We try to use GitHub issues only to track work for developers to do to fix bugs and add new features to this project. This issue is being closed, because it doesn't describe a bug in this project.

There is a mailing list and a Discord channel to support Kivy users debugging their own systems, which should be able to help. They are linked in the [ReadMe](https://github.com/kivy/buildozer#support). Don't forget to mention details about your platform and versions used.

Of course, if it turns out you have stumbled over a bug in this project, we do want to hear about it here. The support channels should be able to help you craft an appropriate bug report.
