### ISSUE TITLE
GPS accuracy

### ISSUE THREAD

**Issue by frankvp11** [kivy/plyer#772]
I was working with the Plyer GPS examples and had some issues. I was trying to figure out the total distance that the user travelled. One important detail is that I added in a map and am plotting the GPS coordinates on there in real time.

The problem that I am dealing with is that it doesn't really appear to be accurate. I've enabled fine precision, but sometimes it will still place me within a field a hundred or so meters away. Also, sometimes it will send me "to the moon" aka very far away and then back very quickly. This again, causes the distance that I am trying to calculate with the Haversine formula to go way to big. In a distance that was supposed to be ~500m it ended up being >5000. 
I know that my GPS does work, as when I go to google maps it is accurate to a couple meters (+- 10m). 
I've tried adding in a threshold for the accuracy (I used 40%), but that didn't improve it at all. 

What am I going to try is to use is the speed, however that would probably still be subject to the same problem as the accuracy did. 

Thanks in advance for any help.

**Comment by frankvp11** [comment]
Is there any update on this? Perhaps any ideas on how I can handle this issue that I am facing?

**Comment by Julian-O** [comment]
👋 Sorry to hear you are having difficulties; Kivy unites a number of different technologies, so developing apps can be temperamental.

We try to use GitHub issues only to track work for developers to do to fix bugs and add new features to this project. This issue is being closed, because it doesn't describe a bug in this project.

There is a mailing list and a Discord channel to support Kivy users debugging their own systems, which should be able to help. They are linked in the [ReadMe](https://github.com/kivy/buildozer#support).

Of course, if it turns out you have stumbled over a bug in this project, we do want to hear about it here. The support channels should be able to help you craft an appropriate bug report.

[This to me sounds like it is just normal GPS unreliability, and Google Maps probably implements sophisticated filters (like Kalman Filters) to clean it up, but this isn't my area, so I may be wrong.]
