### ISSUE TITLE
Persistent notification 

### ISSUE THREAD

**Issue by USER4247** [kivy/plyer#774]
Hi , I have uploads and downloads feature in my app . I have some services that manage these but when app close they terminate . One way to keep services running is persistent notification . Can I make persustant notifications with notification notify function ?

**Comment by Julian-O** [comment]
👋 Sorry to hear you are having difficulties; Kivy unites a number of different technologies, so developing apps can be temperamental.

We try to use GitHub issues only to track work for developers to do to fix bugs and add new features to this project. This issue is being closed, because it doesn't describe a bug in this project.

There is a mailing list and a Discord channel to support Kivy users debugging their own systems, which should be able to help. They are linked in the [ReadMe](https://github.com/kivy/buildozer#support).

Of course, if it turns out you have stumbled over a bug in this project, we do want to hear about it here. The support channels should be able to help you craft an appropriate bug report.
