### ISSUE TITLE
macOS: AttributeError: 'NoneType' object has no attribute 'setDelegate_'

### ISSUE THREAD

**Issue by snoman88** [kivy/plyer#775]
Hi, I'm newbie of player, and my first code occurred an error. What can I do?

Envs:

> Platform: macOS-14.0-arm64-arm-64bit
> conda: 23.7.2
> python: 3.11.5
> plyer: 2.1.0
> 

Code:
`
import plyer

plyer.notification.notify(title='Test', message='This is a test',   app_name='Test App')
`

Result:
Traceback (most recent call last):
  File "/Users/aaa/devs/study/pythonStudy/plyerTest.py", line 7, in <module>
    plyer.notification.notify(title='Test', message='This is a test',   app_name='Test App')
  File "/Users/aaa/anaconda3/envs/cv/lib/python3.11/site-packages/plyer/facades/notification.py", line 84, in notify
    self._notify(
  File "/Users/aaa/anaconda3/envs/cv/lib/python3.11/site-packages/plyer/platforms/macosx/notification.py", line 38, in _notify
    usrnotifctr.setDelegate_(self)
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'setDelegate_'

**Comment by Julian-O** [comment]
👋 Sorry to hear you are having difficulties; Kivy unites a number of different technologies, so developing apps can be temperamental.

We try to use GitHub issues only to track work for developers to do to fix bugs and add new features to this project. This issue is being closed, because it doesn't describe a bug in this project.

There is a mailing list and a Discord channel to support Kivy users debugging their own systems, which should be able to help. They are linked in the [ReadMe](https://github.com/kivy/buildozer#support).

Of course, if it turns out you have stumbled over a bug in this project, we do want to hear about it here. The support channels should be able to help you craft an appropriate bug report.
